version: '3'
services:
  dev:
    build:
      context: .
    image: template
    container_name: template
    volumes:
      - .:/project/.
      # - /app/renv
    working_dir: /project
    tty: true