version: '3'
services:
  project:
    build:
      context: .
    image: blueprint
    container_name: blueprint
    # Mount stuff. Is there a more elegant way to do this?
    volumes:
      - .:/root/project
    working_dir: /root/project
    tty: true
    command: bash